name: workflow.yml
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Conan
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential python3-pip
          pip install conan
          conan profile detect --force
      - name: Install Conan Packages
        run: conan install . --build=missing -s compiler.cppstd=gnu23
      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=build/generators/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build
      - name: Test
        run: ctest --test-dir build --output-on-failure